<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Nilam-KH" name="com.test.java.PricingTest" tests="4" failures="1" timestamp="21 Apr 2017 10:41:36 GMT" time="92.272" errors="0">
  <testcase name="getPricingTest" time="26.112" classname="com.test.java.PricingTest"/>
  <testcase name="getPricingTest" time="9.920" classname="com.test.java.PricingTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	React Operations App And Arbitrage Sales App Not Match expected [Arbitrage Sales App] but found [React Operations App]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	React Operations App And Arbitrage Sales App Not Match expected [Arbitrage Sales App] but found [React Operations App]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.test.java.PricingTest.getPricingTest(PricingTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1240)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- getPricingTest -->
  <testcase name="getPricingTest" time="25.338" classname="com.test.java.PricingTest"/>
  <testcase name="getPricingTest" time="30.902" classname="com.test.java.PricingTest"/>
</testsuite> <!-- com.test.java.PricingTest -->
